### ISSUE TITLE
Capsolver

### ISSUE THREAD

**Issue by Xeeeno** [Y0ngg4n/2captcha-csharp-net#1]
Hey, it's possible that you make one for [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc...
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by Y0ngg4n** [comment]
@Xeeeno no sorry this is just a for of the original project in c# with .NET
